import { CalculatorCategory, CalculatorMeta } from '@/lib/types/calculator.types';

export const CALCULATOR_CATEGORIES: CalculatorCategory[] = [
  'Loans & EMI',
  'Investments',
  'Banking & Interest',
  'Retirement & Savings',
  'Tax & GST',
  'General',
];

export const CALCULATORS_LIST: CalculatorMeta[] = [
  // 1. Loans & EMI
  {
    slug: 'emi-calculator',
    name: 'EMI Calculator',
    shortName: 'Loan EMI',
    description: 'Calculate monthly EMI and total interest payable for home, personal, and car loans with an amortization schedule.',
    category: 'Loans & EMI',
    badge: 'Popular',
    iconName: 'Calculator',
    keywords: ['emi', 'loan', 'home loan', 'personal loan', 'interest', 'monthly installment'],
    popular: true,
  },
  {
    slug: 'car-loan-emi-calculator',
    name: 'Car Loan EMI Calculator',
    shortName: 'Car Loan EMI',
    description: 'Calculate your auto loan monthly installments, total interest, and down payment requirements easily.',
    category: 'Loans & EMI',
    iconName: 'Car',
    keywords: ['car loan', 'auto loan', 'vehicle loan', 'car emi', 'down payment'],
    popular: true,
  },

  // 2. Investments
  {
    slug: 'sip-calculator',
    name: 'SIP Calculator',
    shortName: 'SIP',
    description: 'Estimate future returns and wealth accumulated through monthly Systematic Investment Plans in mutual funds.',
    category: 'Investments',
    badge: 'Most Used',
    iconName: 'TrendingUp',
    keywords: ['sip', 'mutual fund', 'systematic investment', 'wealth creation', 'compounding'],
    popular: true,
  },
  {
    slug: 'swp-calculator',
    name: 'SWP Calculator',
    shortName: 'SWP',
    description: 'Calculate remaining portfolio balance and regular monthly cash flow via Systematic Withdrawal Plans.',
    category: 'Investments',
    iconName: 'Coins',
    keywords: ['swp', 'systematic withdrawal', 'pension', 'monthly cashflow', 'mutual funds'],
  },
  {
    slug: 'lumpsum-calculator',
    name: 'Lumpsum Calculator',
    shortName: 'Lumpsum Investment',
    description: 'Calculate compound returns and maturity value for one-time lumpsum investments in mutual funds or stocks.',
    category: 'Investments',
    iconName: 'Wallet',
    keywords: ['lumpsum', 'one time investment', 'mutual fund lumpsum', 'future value'],
    popular: true,
  },
  {
    slug: 'mutual-fund-calculator',
    name: 'Mutual Fund Calculator',
    shortName: 'Mutual Funds',
    description: 'Compare SIP vs Lumpsum mutual fund returns and forecast your long-term wealth growth.',
    category: 'Investments',
    iconName: 'PieChart',
    keywords: ['mutual fund', 'equity', 'sip or lumpsum', 'fund returns', 'cagr'],
  },
  {
    slug: 'cagr-calculator',
    name: 'CAGR Calculator',
    shortName: 'CAGR',
    description: 'Measure the Compound Annual Growth Rate of your portfolio, stocks, business, or mutual fund investments.',
    category: 'Investments',
    iconName: 'LineChart',
    keywords: ['cagr', 'compound annual growth rate', 'annual return', 'investment performance'],
  },

  // 3. Banking & Interest
  {
    slug: 'simple-interest-calculator',
    name: 'Simple Interest Calculator',
    shortName: 'Simple Interest',
    description: 'Quickly calculate simple interest earned or owed on loans, deposits, and personal borrowings.',
    category: 'Banking & Interest',
    iconName: 'Percent',
    keywords: ['simple interest', 'si', 'pnr/100', 'interest calculation', 'borrowing'],
  },
  {
    slug: 'compound-interest-calculator',
    name: 'Compound Interest Calculator',
    shortName: 'Compound Interest',
    description: 'Simulate the power of compounding with flexible compounding frequencies (monthly, quarterly, annual).',
    category: 'Banking & Interest',
    iconName: 'Sparkles',
    keywords: ['compound interest', 'ci', 'compounding frequency', 'growth', 'wealth multiplier'],
    popular: true,
  },
  {
    slug: 'fd-calculator',
    name: 'FD Calculator (Fixed Deposit)',
    shortName: 'Fixed Deposit (FD)',
    description: 'Calculate maturity amount and quarterly compounded interest on bank fixed deposits across various tenures.',
    category: 'Banking & Interest',
    badge: 'Popular',
    iconName: 'Building2',
    keywords: ['fd', 'fixed deposit', 'bank fd', 'term deposit', 'maturity interest'],
    popular: true,
  },
  {
    slug: 'rd-calculator',
    name: 'RD Calculator (Recurring Deposit)',
    shortName: 'Recurring Deposit (RD)',
    description: 'Calculate maturity value and interest earnings on monthly recurring deposits in Indian banks or post offices.',
    category: 'Banking & Interest',
    iconName: 'Layers',
    keywords: ['rd', 'recurring deposit', 'monthly deposit', 'post office rd', 'bank rd'],
  },
  {
    slug: 'roi-calculator',
    name: 'ROI Calculator (Return on Investment)',
    shortName: 'ROI',
    description: 'Measure profitability, absolute percentage gain, and annualized return on any financial or business investment.',
    category: 'Banking & Interest',
    iconName: 'BarChart3',
    keywords: ['roi', 'return on investment', 'profit percentage', 'gain', 'yield'],
  },

  // 4. Retirement & Savings
  {
    slug: 'ppf-calculator',
    name: 'PPF Calculator (Public Provident Fund)',
    shortName: 'PPF Scheme',
    description: 'Calculate 15-year maturity value, government-backed interest (7.1%), and tax exemption benefits under Section 80C.',
    category: 'Retirement & Savings',
    badge: 'Tax Free',
    iconName: 'ShieldCheck',
    keywords: ['ppf', 'public provident fund', '80c', 'tax free', '15 year deposit'],
    popular: true,
  },
  {
    slug: 'pf-calculator',
    name: 'EPF / PF Calculator',
    shortName: 'EPF / PF',
    description: 'Calculate your accumulated Employee Provident Fund retirement corpus with 8.25% interest and annual salary hikes.',
    category: 'Retirement & Savings',
    iconName: 'Briefcase',
    keywords: ['epf', 'pf', 'provident fund', 'epfo', 'salary contribution', 'retirement corpus'],
    popular: true,
  },
  {
    slug: 'nps-calculator',
    name: 'NPS Calculator (National Pension System)',
    shortName: 'NPS Pension',
    description: 'Plan your retirement with NPS: calculate lump-sum withdrawal at age 60 and regular monthly pension income.',
    category: 'Retirement & Savings',
    badge: '80CCD(1B)',
    iconName: 'Landmark',
    keywords: ['nps', 'national pension scheme', 'pension', 'annuity', '80ccd', 'retirement'],
  },
  {
    slug: 'gratuity-calculator',
    name: 'Gratuity Calculator',
    shortName: 'Gratuity',
    description: 'Calculate eligible gratuity payout on resignation or retirement as per the Payment of Gratuity Act formula.',
    category: 'Retirement & Savings',
    iconName: 'Award',
    keywords: ['gratuity', 'gratuity act', 'resignation payout', '15 days salary', 'retirement benefit'],
  },
  {
    slug: 'ssy-calculator',
    name: 'Sukanya Samriddhi Yojana (SSY) Calculator',
    shortName: 'SSY Scheme',
    description: 'Calculate guaranteed 8.2% tax-free maturity amount for your girl child’s higher education and marriage.',
    category: 'Retirement & Savings',
    badge: '8.2% Return',
    iconName: 'HeartHandshake',
    keywords: ['ssy', 'sukanya samriddhi', 'girl child scheme', 'tax free', 'post office ssy'],
  },
  {
    slug: 'post-office-mis-calculator',
    name: 'Post Office MIS Calculator',
    shortName: 'Post Office MIS',
    description: 'Calculate guaranteed monthly income and interest payout from Post Office Monthly Income Scheme.',
    category: 'Retirement & Savings',
    iconName: 'Mail',
    keywords: ['post office mis', 'monthly income scheme', 'pomis', 'guaranteed income', 'post office deposit'],
  },
  {
    slug: 'retirement-planning-calculator',
    name: 'Retirement Planning Calculator',
    shortName: 'Retirement Goal',
    description: 'Calculate inflation-adjusted retirement corpus needed and required monthly SIP savings to maintain your lifestyle.',
    category: 'Retirement & Savings',
    iconName: 'Compass',
    keywords: ['retirement planning', 'inflation adjusted', 'target corpus', 'financial freedom', 'fire'],
    popular: true,
  },
  {
    slug: 'kvp-calculator',
    name: 'Kisan Vikas Patra (KVP) Calculator',
    shortName: 'Kisan Vikas Patra',
    description: 'Calculate the maturity value and exact doubling period (115 months) for Post Office KVP certificates.',
    category: 'Retirement & Savings',
    iconName: 'Wheat',
    keywords: ['kvp', 'kisan vikas patra', 'double money', 'post office scheme', 'guaranteed returns'],
  },

  // 5. Tax & GST
  {
    slug: 'income-tax-calculator',
    name: 'Income Tax Calculator (FY 2024-25 & 2025-26)',
    shortName: 'Income Tax (Old vs New)',
    description: 'Compare Old vs New Tax Regime side-by-side with updated Budget 2024 slabs, Standard Deduction (₹75K), and 87A rebate.',
    category: 'Tax & GST',
    badge: 'Budget 2024',
    iconName: 'FileSpreadsheet',
    keywords: ['income tax', 'tax calculator', 'old vs new regime', 'tax slabs', 'standard deduction', 'section 87a'],
    popular: true,
  },
  {
    slug: 'ltcg-calculator',
    name: 'LTCG Tax Calculator (Long Term Capital Gains)',
    shortName: 'LTCG Tax',
    description: 'Calculate capital gains tax on equity, mutual funds, and real estate with the new 12.5% rate & ₹1.25L exemption.',
    category: 'Tax & GST',
    iconName: 'BadgePercent',
    keywords: ['ltcg', 'long term capital gain', 'capital gains tax', '12.5 percent', 'equity ltcg', 'budget 2024'],
  },
  {
    slug: 'gst-calculator',
    name: 'GST Calculator (Inclusive & Exclusive)',
    shortName: 'GST Calculator',
    description: 'Calculate GST (5%, 12%, 18%, 28%) with instant CGST, SGST, IGST breakdown for inclusive and exclusive amounts.',
    category: 'Tax & GST',
    badge: 'Instant',
    iconName: 'Receipt',
    keywords: ['gst', 'cgst', 'sgst', 'igst', 'inclusive gst', 'exclusive gst', 'tax invoice'],
    popular: true,
  },
  {
    slug: 'gstr3b-interest-calculator',
    name: 'GSTR-3B Interest Calculator',
    shortName: 'GSTR-3B Interest',
    description: 'Calculate Section 50(1) delay interest at 18% p.a. on delayed GST payments and return filing.',
    category: 'Tax & GST',
    iconName: 'Clock',
    keywords: ['gstr-3b', 'gst interest', 'section 50', 'late gst filing', 'delay interest 18%'],
  },
  {
    slug: 'tax-saving-calculator',
    name: 'Tax Saving Calculator (80C, 80D, NPS)',
    shortName: 'Tax Saving Options',
    description: 'See how much tax you save by investing in 80C (PPF, ELSS, EPF), 80D (Health Insurance), and 80CCD (NPS).',
    category: 'Tax & GST',
    iconName: 'ShieldPlus',
    keywords: ['tax saving', '80c', '80d', 'elss', 'health insurance deduction', 'tax deductions'],
  },
  {
    slug: 'salary-calculator',
    name: 'In-Hand Salary Calculator (Take Home Pay)',
    shortName: 'Take Home Salary',
    description: 'Break down your CTC into monthly in-hand take home, Basic, HRA, EPF, Professional Tax, and estimated TDS.',
    category: 'Tax & GST',
    iconName: 'DollarSign',
    keywords: ['salary calculator', 'take home salary', 'ctc to in hand', 'net salary', 'gross salary', 'epf deduction'],
    popular: true,
  },

  // 6. General
  {
    slug: 'discount-calculator',
    name: 'Discount Calculator',
    shortName: 'Discount & Savings',
    description: 'Calculate final discounted price, total amount saved, and percentage discount on products and invoices.',
    category: 'General',
    iconName: 'Tag',
    keywords: ['discount', 'sale', 'percentage off', 'price reduction', 'savings'],
  },
];
